// Will be automatically generated by react-imported-component
import { assignImportedComponents } from 'react-imported-component'
const applicationImports = {}
assignImportedComponents(applicationImports)
export default applicationImports
